-- models/star_schema.sql
-- ----------------------
-- Kimball star schema DDL for the Financial Lineage Pipeline.
-- Executed against DuckDB at pipeline load stage.
--
-- Schema:
--   FactTrades         : central fact table — one row per trade
--   DimProduct         : product/instrument dimension
--   DimCounterparty    : counterparty/legal entity dimension
--   DimDate            : calendar date dimension
--   DimSettlementStatus: settlement status conformed dimension
--
-- Naming conventions:
--   - Dimension tables prefixed with dim_
--   - Fact tables prefixed with fact_
--   - Surrogate keys: <table>_key (INTEGER)
--   - Natural/business keys preserved as _id columns
--   - Timestamps stored as TIMESTAMP, dates as DATE
--
-- Populated by:
--   etl/transforms/     -> enriched DataFrame written here at load stage
--   scripts/            -> seed scripts for dimension tables
--
-- Queried by:
--   dashboard/pages/    -> Streamlit dashboard pages
--   dq/violation_logger.py -> referential integrity DQ lookups

-- ===========================================================================
-- DIMENSION TABLES
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- DimDate
-- Pre-populated with all calendar dates for the trading period.
-- Generated by scripts/generate_sample_data.py or a seed script.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS dim_date (
    date_key        INTEGER PRIMARY KEY,   -- YYYYMMDD integer surrogate key
    calendar_date   DATE        NOT NULL,
    year            INTEGER     NOT NULL,
    quarter         INTEGER     NOT NULL   CHECK (quarter BETWEEN 1 AND 4),
    month           INTEGER     NOT NULL   CHECK (month BETWEEN 1 AND 12),
    month_name      VARCHAR(9)  NOT NULL,
    day_of_week     INTEGER     NOT NULL   CHECK (day_of_week BETWEEN 1 AND 7),
    day_name        VARCHAR(9)  NOT NULL,
    is_month_end    BOOLEAN     NOT NULL   DEFAULT FALSE,
    is_quarter_end  BOOLEAN     NOT NULL   DEFAULT FALSE,
    is_year_end     BOOLEAN     NOT NULL   DEFAULT FALSE,
    is_trading_day  BOOLEAN     NOT NULL   DEFAULT TRUE,  -- FALSE for weekends/holidays
    fiscal_year     INTEGER     NOT NULL,
    fiscal_quarter  INTEGER     NOT NULL   CHECK (fiscal_quarter BETWEEN 1 AND 4)
);

CREATE INDEX IF NOT EXISTS idx_dim_date_calendar ON dim_date (calendar_date);
CREATE INDEX IF NOT EXISTS idx_dim_date_year_month ON dim_date (year, month);


-- ---------------------------------------------------------------------------
-- DimProduct
-- Financial instruments and securities reference data.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS dim_product (
    product_key     INTEGER PRIMARY KEY,
    product_id      VARCHAR(50)  NOT NULL UNIQUE,   -- natural business key
    ticker          VARCHAR(20),
    isin            VARCHAR(12),                     -- ISO 6166 security identifier
    cusip           VARCHAR(9),
    sedol           VARCHAR(7),
    asset_class     VARCHAR(50)  NOT NULL,            -- Equity | FX | Rates | Credit | Commodity
    sub_asset_class VARCHAR(100),
    currency        VARCHAR(3)   NOT NULL,            -- ISO 4217 currency code
    exchange        VARCHAR(10),                     -- NYSE | LSE | TSE | XETRA etc.
    country         VARCHAR(2),                      -- ISO 3166 country code
    is_active       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_dim_product_asset_class ON dim_product (asset_class);
CREATE INDEX IF NOT EXISTS idx_dim_product_currency ON dim_product (currency);
CREATE INDEX IF NOT EXISTS idx_dim_product_exchange ON dim_product (exchange);


-- ---------------------------------------------------------------------------
-- DimCounterparty
-- Legal entity reference data with LEI codes.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS dim_counterparty (
    counterparty_key    INTEGER PRIMARY KEY,
    counterparty_id     VARCHAR(50)  NOT NULL UNIQUE,  -- natural business key
    legal_entity_name   VARCHAR(200) NOT NULL,
    lei_code            VARCHAR(20),                   -- GLEIF LEI (20 chars)
    lei_country         VARCHAR(2),                    -- ISO 3166
    credit_rating       VARCHAR(10),                   -- AA | A+ | BBB+ etc.
    rating_agency       VARCHAR(50),                   -- S&P | Moody's | Fitch
    country             VARCHAR(2),
    city                VARCHAR(100),
    entity_type         VARCHAR(50),                   -- Bank | Fund | Broker | Corporate
    is_internal         BOOLEAN     NOT NULL DEFAULT FALSE,
    is_active           BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_dim_cpty_lei ON dim_counterparty (lei_code);
CREATE INDEX IF NOT EXISTS idx_dim_cpty_country ON dim_counterparty (lei_country);
CREATE INDEX IF NOT EXISTS idx_dim_cpty_rating ON dim_counterparty (credit_rating);


-- ---------------------------------------------------------------------------
-- DimSettlementStatus
-- Conformed dimension for settlement status codes.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS dim_settlement_status (
    status_key      INTEGER PRIMARY KEY,
    status_code     VARCHAR(20)  NOT NULL UNIQUE,  -- SETTLED | PENDING | FAILED | CANCELLED
    status_label    VARCHAR(50)  NOT NULL,
    is_terminal     BOOLEAN      NOT NULL,          -- TRUE if no further state changes expected
    requires_action BOOLEAN      NOT NULL DEFAULT FALSE
);

-- Seed settlement status dimension
INSERT OR IGNORE INTO dim_settlement_status VALUES
    (1, 'SETTLED',   'Settled',            TRUE,  FALSE),
    (2, 'PENDING',   'Pending Settlement', FALSE, FALSE),
    (3, 'FAILED',    'Failed',             TRUE,  TRUE),
    (4, 'CANCELLED', 'Cancelled',          TRUE,  FALSE),
    (5, 'UNKNOWN',   'Unknown',            FALSE, TRUE);


-- ===========================================================================
-- FACT TABLE
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- FactTrades
-- Central fact table — one row per trade after full ETL processing.
-- References all four dimension tables via surrogate keys.
-- Contains both raw and enriched measure columns.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS fact_trades (
    -- Surrogate key
    trade_key               BIGINT PRIMARY KEY,

    -- Dimension foreign keys
    product_key             INTEGER     REFERENCES dim_product(product_key),
    counterparty_key        INTEGER     REFERENCES dim_counterparty(counterparty_key),
    trade_date_key          INTEGER     REFERENCES dim_date(date_key),
    settlement_date_key     INTEGER     REFERENCES dim_date(date_key),
    status_key              INTEGER     REFERENCES dim_settlement_status(status_key),

    -- Business / natural key
    trade_id                VARCHAR(50)  NOT NULL UNIQUE,

    -- Core measures — raw
    notional                DOUBLE       NOT NULL,
    quantity                DOUBLE       NOT NULL,
    currency                VARCHAR(3)   NOT NULL,
    direction               VARCHAR(10)  NOT NULL   CHECK (direction IN ('BUY', 'SELL', 'UNKNOWN')),

    -- Enriched measures — FX converted
    notional_usd            DOUBLE,
    notional_eur            DOUBLE,
    fx_rate_to_usd          DOUBLE,

    -- Enriched measures — position netting
    buy_notional_usd        DOUBLE,
    sell_notional_usd       DOUBLE,
    net_notional_usd        DOUBLE,

    -- Enriched measures — counterparty exposure (window aggregates)
    cpty_total_notional_usd DOUBLE,
    cpty_trade_count        INTEGER,
    running_notional_usd    DOUBLE,
    asset_class_exposure_usd DOUBLE,

    -- Calendar degenerate dimensions
    trade_year              INTEGER,
    trade_quarter           INTEGER,
    trade_month             INTEGER,
    trade_day_of_week       INTEGER,
    is_month_end            BOOLEAN,
    is_trading_day          BOOLEAN,
    days_to_settlement      INTEGER,

    -- Pipeline metadata
    batch_id                VARCHAR(30)  NOT NULL,
    pipeline_name           VARCHAR(100),
    loaded_at               TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dq_score_at_load        DOUBLE                                          -- DQ score of the batch
);

-- Indexes for common query patterns
CREATE INDEX IF NOT EXISTS idx_fact_trades_trade_date   ON fact_trades (trade_date_key);
CREATE INDEX IF NOT EXISTS idx_fact_trades_counterparty ON fact_trades (counterparty_key);
CREATE INDEX IF NOT EXISTS idx_fact_trades_product      ON fact_trades (product_key);
CREATE INDEX IF NOT EXISTS idx_fact_trades_batch        ON fact_trades (batch_id);
CREATE INDEX IF NOT EXISTS idx_fact_trades_direction    ON fact_trades (direction);
CREATE INDEX IF NOT EXISTS idx_fact_trades_currency     ON fact_trades (currency);


-- ===========================================================================
-- ANALYTICAL VIEWS
-- ===========================================================================

-- Operational metadata tables may be created by Python during normal pipeline
-- runs. Define the DQ score table here as well so schema bootstrap can create
-- views before any DQ checkpoint has executed.
CREATE TABLE IF NOT EXISTS dq_scores (
    batch_id         VARCHAR,
    checkpoint       VARCHAR,
    rules_run        INTEGER,
    rules_passed     INTEGER,
    rules_failed     INTEGER,
    total_violations INTEGER,
    critical_count   INTEGER,
    error_count      INTEGER,
    warn_count       INTEGER,
    dq_score         DOUBLE,
    duration_sec     DOUBLE,
    recorded_at      VARCHAR
);

-- Daily exposure by counterparty
CREATE OR REPLACE VIEW vw_daily_cpty_exposure AS
SELECT
    d.calendar_date,
    c.legal_entity_name,
    c.lei_code,
    c.credit_rating,
    f.currency,
    SUM(f.notional_usd)    AS total_notional_usd,
    SUM(f.notional_eur)    AS total_notional_eur,
    SUM(f.net_notional_usd) AS net_notional_usd,
    COUNT(*)               AS trade_count
FROM fact_trades f
JOIN dim_date         d ON f.trade_date_key    = d.date_key
JOIN dim_counterparty c ON f.counterparty_key  = c.counterparty_key
GROUP BY
    d.calendar_date,
    c.legal_entity_name,
    c.lei_code,
    c.credit_rating,
    f.currency;


-- Asset class exposure summary
CREATE OR REPLACE VIEW vw_asset_class_exposure AS
SELECT
    p.asset_class,
    p.currency,
    d.year,
    d.quarter,
    SUM(f.notional_usd)     AS total_notional_usd,
    SUM(f.net_notional_usd) AS net_notional_usd,
    COUNT(*)                AS trade_count,
    COUNT(DISTINCT f.counterparty_key) AS unique_counterparties
FROM fact_trades f
JOIN dim_product p ON f.product_key   = p.product_key
JOIN dim_date    d ON f.trade_date_key = d.date_key
GROUP BY
    p.asset_class,
    p.currency,
    d.year,
    d.quarter;


-- Settlement failure analysis
CREATE OR REPLACE VIEW vw_settlement_failures AS
SELECT
    f.trade_id,
    f.trade_date_key,
    f.notional_usd,
    f.currency,
    c.legal_entity_name,
    c.credit_rating,
    p.asset_class,
    s.status_label,
    f.days_to_settlement,
    f.batch_id
FROM fact_trades f
JOIN dim_settlement_status s ON f.status_key       = s.status_key
JOIN dim_counterparty      c ON f.counterparty_key = c.counterparty_key
JOIN dim_product           p ON f.product_key      = p.product_key
WHERE s.status_code = 'FAILED';


-- DQ score trend across batches
CREATE OR REPLACE VIEW vw_dq_score_trend AS
SELECT
    batch_id,
    checkpoint,
    dq_score,
    rules_run,
    rules_passed,
    rules_failed,
    total_violations,
    critical_count,
    error_count,
    warn_count,
    recorded_at
FROM dq_scores
ORDER BY recorded_at DESC;